# Ubuntu version (ubuntu, ubuntu22.04, ubuntu20.04, ubuntu18.04)
# Debian version (debian, debian12, debian11 or debian10)
# Alpine version (alpine, alpine3.16, alpine3.17, alpine3.18)
# Full list https://mcr.microsoft.com/en-us/product/devcontainers/base/about
ARG VARIANT=ubuntu
FROM mcr.microsoft.com/devcontainers/base:${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>